### ISSUE TITLE
Fran banck: no carga datos de 'stack'

### ISSUE THREAD

**Issue by DanielBanobreDopico** [CesarLealPerez/Officium#19]

**Comment by kaotikodesign** [comment]
En la consola del navegador, accediendo a los "staks" de LocalStorage, aparecen vacios, no sé, si es por que no los crea, o simplemente no los lee

**Comment by DanielBanobreDopico** [comment]
Creo que deberían de ser "tasks" en lugar de "staks".

**Comment by kaotikodesign** [comment]
Si, fallo al comentar, pone "tasks".

**Comment by DanielBanobreDopico** [comment]
La primera vez que se ejecuta tienen que aparecer vacios. En localStorage deberian de aparecer como "[]".
Si necesitas que tengan contenido para probar tus componentes puedes darle contenido: $tasks = [{...},{...}] con objetos con las propiedades segun las especificaciones.

**Comment by DanielBanobreDopico** [comment]
Al hacer la asignacion los cambios deberian de aparecer en el local storage y conservarse en futuras ejecuciones.

**Comment by kaotikodesign** [comment]
Solucionado (En principio)
En vez de:
 $tasks.push(NuevoProyecto)
lo cambié por: 
$tasks = $tasks.push(NuevoProyecto)

**Comment by DanielBanobreDopico** [comment]
Ok. En ese caso cierro.
