### ISSUE TITLE
Como subir una app a Google Play

### ISSUE THREAD

**Issue by rubenterre** [CesarLealPerez/Officium#20]
**Como subir tu app a Google Play**

Antes de comenzar con los pasos es necesario obtener un archivo APK de nuestra aplicación, dependiendo de las tecnologías que hayamos utilizado podemos realizarlo de varias formas: 

- Obteniéndolo con la tecnología de [Apache Cordova](https://cordova.apache.org/) que podríamos usar más fácilmente si usamos previamente Framework7 con la opción de Cordova. => [Instrucciones para crear una apk en Cordova](https://medium.com/@emmanuel.haankwenda2018/how-to-create-an-android-or-ios-app-with-framework7-and-cordova-e1b8dbdfc396)

- Obteniéndolo a través de [Android Studio](https://developer.android.com/studio) con el cual también conseguiremos fácilmente la firma (keystore) con lo que es bastante recomendable, sobre todo si solo hemos usado tecnologías web para realizarla (HTML, CSS y JS) o hemos usado Svelte y tenemos nuestros archivos subidos a un servidor con una URL protegida con SSL (https) (**Muy importante** tener una URL encriptada puesto que si no no funcionará).

- También existen otros programas que te generan el APK con un enlace a una web o con una carpeta con los archivos web dentro. Estamos hablando de programas como [Website2APK](https://websitetoapk.com/), [Convertify](https://convertify.app/) o [WebViewGold](https://www.webviewgold.com/) que te ahorran muchísimo tiempo a cambio de un módico precio.

- Por último, podemos también convertir nuestra web en una TWA que luego podremos publicar en la Google Play, esto viene a ser una PWA preparada para publicarse como una APK => [Instrucciones](https://victor-mochere.com/es/how-to-publish-a-pwa-on-google-play-store)

De estas opciones yo **recomiendo la segunda**. De tal forma que podemos publicar desde una PWA a una app hecha con Svelte de la misma manera. => [Instrucciones](https://www.gestionatuweb.net/crear-webview-con-android-studio-para-cargar-una-web-en-una-app-android/) aunque también recomiendo ver los tutoriales de MoureDev sobre el tema => [Videotutorial](https://www.youtube.com/watch?v=qwb8qSw1d7s)

Al terminar es **MUY IMPORTANTE** **guardar el archivo keystore a buen recaudo** y tener claro cuáles son los credenciales que hemos puesto allí. Esto será necesario para futuras actualizaciones de la aplicación. Una vez firmada y publicada en la Google Play sólo servirá esa firma, si la pierdes no podrás volver a modificar la aplicación. 

Una vez hecho esto nos dirigiremos a la Google Console Play.

1. Entras en la web de [Google Console Play](https://developer.android.com/distribute/console?hl=es)

2. Para poder gestionar todos los procesos desde la publicación hasta el marketing de la aplicación necesitamos una cuenta de _desarrollador de Google_ para ello pulsamos en el botón ACCEDER que hay en el banner central de la página de Google Console Play.

3. Una vez pulsemos el botón **ACCEDER** tendremos que loguearnos con nuestra cuenta de Google si no lo hemos hecho aún y cubrir el formulario siguiendo paso a paso todo el proceso y al final **pagar el certificado** de desarrollador de Google que actualmente está en 25$ (23€) y es para toda la vida.

4. Si todo va bien acabaremos en el panel del Google Console Play en donde nos muestran todos los pasos que debemos seguir para poder publicar nuestra aplicación. Lo primero que debemos hacer es pulsar el botón **Crear aplicación** y cubrir el formulario con los datos básicos de la app y aceptar los términos para poder continuar con el siguiente proceso.

5. En la siguiente pantalla nos encontraremos en el **Panel de control** en el que debajo se suceden varias secciones. De estas secciones es importante cubrir la primera llamada **Primeros pasos** por lo que pulsaremos en el botón **Primeros pasos** y se nos desplegará un listado con los pasos que debemos de ir cubriendo. A medida que vamos cubriendo y guardado las preferencias y opciones veremos como se van tachando en el listado los pasos cumplimentados. Es **importante cubrirlo todo** y no dejarse ningún paso sin hacer para que luego no tengamos problemas con la revisión de la app por parte de Google.

6. Una vez que ya hayamos terminado con todo el listado no es necesario continuar con los siguientes desplegables, son herramientas opcionales que nos ofrece Google para poder testar nuestra aplicación antes de sacarla a producción. Si simplemente queremos publicar nuestra app directamente iremos a la opción **Producción** del sidebar izquierdo de la web. Una vez allí creamos una versión pulsando en el botón **Crear versión** que podemos encontrar en varias partes de la página, arriba en la esquina superior derecha o en el centro del apartado Panel de control de versión si no hay ninguna versión creada todavía.

7. Una vez entramos en **Crear versión** nos lleva al panel de **Crear versión de producción** en el cual deberemos de seguir los pasos. El primero de ellos es **Firma de aplicaciones de Google Play** yo recomiendo darle permiso a Google para que conserve tu **Keystore** por si en el futuro la pierdes siempre quede aquí guardada puesto que si no tienes la misma es imposible poder actualizar la aplicación de nuevo.

A continuación en **App bundles y APKs** debemos subir nuestro archivo APK y en el siguiente apartado de **Detalles de la versión** cubrir las notas de la versión dentro de los paréntesis del idioma (<es-ES>). En estas notas introduciremos los cambios que hemos realizado en esta versión, las mejoras o nuevas funcionalidades que hemos añadido.

8. Finalmente pulsamos en **Revisar** y confiamos en que Google en un periodo máximo de 24h nos publique la app en su tienda.

**Comment by DanielBanobreDopico** [comment]
Epa!
Mola. Gracias!.
A ver cuando puedo mirarlo con calma. Que parece que hace referencias con mucho contenido.
Abrí una página en el WiKi. para el tema. ¿Haces un copy-paste del markdown en la página y así queda en el sitio?. Te pido que lo hagas tú para que figure como tu aportación.
[Enlace al WiKi](https://github.com/CesarLealPerez/Officium/wiki/Publicar-en-Google-Play-Store)
👍🏼

**Comment by rubenterre** [comment]
> Epa!
> Mola. Gracias!.
> A ver cuando puedo mirarlo con calma. Que parece que hace referencias con mucho contenido.
> Abrí una página en el WiKi. para el tema. ¿Haces un copy-paste del markdown en la página y así queda en el sitio?. Te pido que lo hagas tú para que figure como tu aportación.
> [Enlace al WiKi](https://github.com/CesarLealPerez/Officium/wiki/Publicar-en-Google-Play-Store)
> 👍🏼

Lo he pasado al enlace de la Wiki 👍

**Comment by DanielBanobreDopico** [comment]
❤️
