### ISSUE TITLE
No funciona PWA en proyecto whatson

### ISSUE THREAD

**Issue by josemanuelgarciasoto** [CesarLealPerez/Officium#31]
Poniendo los 3 archivos, manifest, sw y runworker no aparece el icono de crear aplicacion.
Me echo una mano Ruben y lo unico que sacamos es que si ya estuviera instalado daría la opción de abrir, y el error de resolución de favicon solucionado.

Muestra que el sw esta activo en f12 pero no aparece. Tambien buscamos que fuera el package.json del frontend dentro de svelte_app.

PD: en firefox sigue sin funcionar tu ejemplo PWA tanto en la nighty como en firefox normal.

Consola:

Puedes usar los serviceWorker en tu navegador
runWorker.js:5 serviceWorker cargado correctamente ServiceWorkerRegistrationactive: ServiceWorker {scriptURL: "http://localhost:62721/sw.js", state: "activated", onstatechange: null, onerror: null}backgroundFetch: BackgroundFetchManager {}installing: nullnavigationPreload: NavigationPreloadManager {}onupdatefound: nullpaymentManager: PaymentManager {instruments: PaymentInstruments, userHint: ""}periodicSync: PeriodicSyncManager {}pushManager: PushManager {}scope: "http://localhost:62721/"sync: SyncManager {}updateViaCache: "imports"waiting: null__proto__: ServiceWorkerRegistration
:35730/livereload.js?snipver=1:1 Failed to load resource: net::ERR_FAILED
sw.js:30 [Service Worker] Fetching resource: http://localhost:62721/
sw.js:30 [Service Worker] Fetching resource: http://localhost:62721/global.css
sw.js:30 [Service Worker] Fetching resource: http://localhost:62721/build/bundle.css
sw.js:30 [Service Worker] Fetching resource: https://cdn.rawgit.com/Chalarangelo/mini.css/v3.0.1/dist/mini-default.min.css
sw.js:30 [Service Worker] Fetching resource: http://localhost:62721/webmanifest.json
DevTools failed to load SourceMap: Could not load content for http://localhost:62721/build/bundle.js.map: Connection error: net::ERR_CONNECTION_REFUSED
DevTools failed to load SourceMap: Could not load content for http://localhost:62721/build/bundle.css.map: Connection error: net::ERR_CONNECTION_REFUSED

**Comment by DanielBanobreDopico** [comment]
Si no me estoy liando este es el problema que se solucionó cambiando el fichero favicon.png que proporciona Svelte por otro de mayor resolución. La resolución mínima recomendable para usar un fichero como icono de PWA es de 192x192 pixeles. 
Por otra parte se están definiendo estándares sobre la presentación de la imagen del icono. Puede ser interesante [este artículo](https://css-tricks.com/maskable-icons-android-adaptive-icons-for-your-pwa/).

Al respecto de Firefox, en las versiones de escritorio no ofrece por el momento la posibilidad de instalar PWA, a menos que activemos esa funcionalidad manualmente. [Aquí se puede ver](https://caniuse.com/web-app-manifest) que PWA se está implementando más rápidamente en los dispositivos móviles que en el escritorio.
