### ISSUE TITLE
Error para hacer pull

### ISSUE THREAD

**Issue by kaotikodesign** [CesarLealPerez/Officium#34]
devel@depeloper-vm:~/Escritorio/Practicas/Officium$ git pull
error: object file .git/objects/23/3423bf641ee14af91d64f2611e5b0e79cd6675 is empty
error: object file .git/objects/23/3423bf641ee14af91d64f2611e5b0e79cd6675 is empty
fatal: loose object 233423bf641ee14af91d64f2611e5b0e79cd6675 (stored in .git/objects/23/3423bf641ee14af91d64f2611e5b0e79cd6675) is corrupt
fatal: The remote end hung up unexpectedly

@DanielBanobreDopico

**Comment by DanielBanobreDopico** [comment]
Por lo que leo es un problema con el tamaño de la descarga. Parece que [la solución](https://thomas-cokelaer.info/blog/2019/08/git-error-solved-the-remote-end-hung-up-unexpectedly/) es aumentar el tamaño del buffer de datos que usa git:
```bash
$ export GIT_HTTP_MAX_REQUEST_BUFFER=100M
$ git pull
```
Sería interesante saber qué lo ha probocado: demasiado tiempo sin hacer pull, todos los merge realizados ayer, la incorporación de ficheros grandes al proyecto...

Si con esto se soluciona, cerrad el issue, de otro modo avisadme.

**Comment by kaotikodesign** [comment]
/* Introduzco el comando pero continua con el mismo error, por norma general hacia 1 o 2 pull al dia por mantenerme actualizado */

devel@depeloper-vm:~/Escritorio/Practicas/Officium$ export GIT_HTTP_MAX_REQUEST_BUFFER=100M
devel@depeloper-vm:~/Escritorio/Practicas/Officium$ git pull
error: object file .git/objects/23/3423bf641ee14af91d64f2611e5b0e79cd6675 is empty
error: object file .git/objects/23/3423bf641ee14af91d64f2611e5b0e79cd6675 is empty
fatal: loose object 233423bf641ee14af91d64f2611e5b0e79cd6675 (stored in .git/objects/23/3423bf641ee14af91d64f2611e5b0e79cd6675) is corrupt
fatal: The remote end hung up unexpectedly
devel@depeloper-vm:~/Escritorio/Practicas/Officium$

**Comment by DanielBanobreDopico** [comment]
He encontrado una solución [más específica](https://stackoverflow.com/questions/4254389/git-corrupt-loose-object#answer-18238322)... pero la veo compleja.

Si no tienes cambios que subir a GitHub, yo creo que es más facil que borres toda la carpeta del proyecto y hagas un `git clone`.

Si tienes cosas que subir y tienes controlados los ficheros a los que afecta, puedes copiarlos antes de borrar y después de crear tu rama incorporar los ficheros nuevamente.

Si no sabes los ficheros afectados, si ya están en un commit, puedes ver el código del commit con `git log` y los ficheros incorporados en el con `git show codigoDelCommit`.

Si no están en un commit, puedes ver qué ficheros han cambiado desde el último commit con `git status`.

**Comment by kaotikodesign** [comment]
el *Git log* da el mismo fallo.
el *Git branch -a* tambien da el mismo fallo (git branch (local) no da fallo)

**Comment by DanielBanobreDopico** [comment]
Si no tienes cosas pendientes de subir, borra y haz un clone nuevo.
Si tienes cosas pendientes de subir, puedes intentar localizar los archivos modificados por la fecha.
Si de esa manera tampoco los puedes localizar, te va a tocar seguir las [instrucciones de esta solución](https://stackoverflow.com/questions/4254389/git-corrupt-loose-object#answer-18238322).

**Comment by kaotikodesign** [comment]
hice el clone, de todas formas hay muchisimos errores, incluso algunos que ya se habian solucionado.
cierro inssue y veo para solucionar.
